# Generated by Django 5.1.4 on 2024-12-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_jobapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
            ),
        ),
    ]
