# Generated by Django 5.1.4 on 2024-12-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_jobapplication_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="company",
            new_name="company_name",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="created_at",
            new_name="posted_at",
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="JobApplication",
        ),
    ]
