# Generated by Django 5.1.4 on 2025-01-22 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobseeker_profile",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
