# Generated by Django 5.1.4 on 2025-01-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_remove_job_company_name_job_applicant_job_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.employerprofile"
            ),
        ),
    ]
