# Generated by Django 5.1.4 on 2025-02-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="employer_profiles/"
            ),
        ),
    ]
