# Generated by Django 5.1.4 on 2025-02-06 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_employer_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employer",
            name="profile_picture",
        ),
    ]
